# Generated by Django 2.2.1 on 2019-05-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfproduct',
            name='brief',
            field=models.CharField(max_length=50, verbose_name='产品摘要'),
        ),
        migrations.AlterField(
            model_name='chfproduct',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ChfProductType', verbose_name='产品类型'),
        ),
    ]
