# Generated by Django 2.2.2 on 2019-06-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfindexplate',
            name='descr',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='简介'),
        ),
    ]
