# Generated by Django 3.0.5 on 2020-06-27 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChfCompet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='标题(中文)')),
                ('en_title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='标题(英文)')),
                ('slug', models.SlugField(blank=True, help_text='根据title生成的，用于生成页面URL，必须唯一', max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='描述(中文)')),
                ('en_content', models.TextField(blank=True, default='', null=True, verbose_name='描述(英文)')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '工作机会',
                'verbose_name_plural': '工作机会',
                'db_table': 'chf_compet',
                'ordering': ['sort', '-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='address',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='底部显示地址(中文)'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='en_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='底部显示地址(英文)'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='en_icp',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='备案号(英文)'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='en_site_company',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='公司(英文)'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='icp',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='备案号(中文)'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='site_company',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='公司(中文)'),
        ),
        migrations.AlterField(
            model_name='sysnav',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='链接'),
        ),
    ]
