# Generated by Django 2.2.1 on 2019-05-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfproduct',
            name='brief',
            field=models.CharField(max_length=40, verbose_name='产品摘要'),
        ),
    ]
