# Generated by Django 2.2.1 on 2019-05-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190504_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfpartner',
            name='brief',
            field=models.CharField(max_length=100, verbose_name='简介'),
        ),
    ]
