# Generated by Django 2.2.2 on 2019-06-27 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190627_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysnav',
            name='code',
            field=models.CharField(default=None, max_length=20, verbose_name='标识'),
        ),
        migrations.CreateModel(
            name='ChfBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('image_url', models.ImageField(blank=True, default=None, null=True, upload_to='banner/%Y/%m', verbose_name='图片')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('nav', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav', related_query_name='nav_query', to='home.SysNav', verbose_name='Banner页面')),
            ],
            options={
                'verbose_name': 'Banner管理',
                'verbose_name_plural': 'Banner管理',
                'db_table': 'chf_banner',
                'ordering': ['sort', '-create_time'],
            },
        ),
    ]
