# Generated by Django 2.2.1 on 2019-06-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190602_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='chfproduct',
            name='mall_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='在线商城地址'),
        ),
    ]
