# Generated by Django 2.2.1 on 2019-05-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190504_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chfproduct',
            old_name='descr',
            new_name='content',
        ),
    ]
