# Generated by Django 2.2.1 on 2019-05-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190531_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfapplyrecord',
            name='birthday',
            field=models.DateField(blank=None, default=None, null=None, verbose_name='生日'),
        ),
    ]
