# Generated by Django 3.0.5 on 2020-06-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200627_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfcompetvideo',
            name='brief',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='摘要(中文)'),
        ),
        migrations.AlterField(
            model_name='chfcompetvideo',
            name='en_brief',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='摘要(英文)'),
        ),
    ]
