# Generated by Django 2.2.1 on 2019-06-20 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190615_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChfCooperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='内容')),
                ('type', models.CharField(choices=[('0', '合作政策'), ('1', '项目优势'), ('2', '经销商问答')], default=0, max_length=10, verbose_name='类型')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '合作共赢',
                'verbose_name_plural': '合作共赢',
                'db_table': 'chf_cooperation',
                'ordering': ['-create_time'],
            },
        ),
        migrations.DeleteModel(
            name='ChfCooperationPolicy',
        ),
        migrations.DeleteModel(
            name='ChfCooperationQuestion',
        ),
        migrations.DeleteModel(
            name='ChfCooperationSuperiority',
        ),
    ]
