# Generated by Django 2.2.2 on 2019-06-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190627_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfbanner',
            name='nav',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navs', related_query_name='nav_query', to='home.SysNav', verbose_name='Banner页面'),
        ),
    ]
