# Generated by Django 2.2.1 on 2019-06-03 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_chfproduct_mall_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChfIndexPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('title', models.CharField(default=None, max_length=8, verbose_name='板块标题')),
                ('plate_image_url', models.ImageField(blank=True, max_length=255, null=True, upload_to='index_plate/%Y/%m', verbose_name='图标')),
                ('front_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='index_plate/%Y/%m', verbose_name='正面图')),
                ('back_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='index_plate/%Y/%m', verbose_name='背面图')),
                ('desc', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='简介')),
                ('is_sub_page', models.BooleanField(default=True, verbose_name='是否跳转到子页面')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '首页板块',
                'verbose_name_plural': '首页板块',
                'db_table': 'chf_indexplate',
                'ordering': ['sort', '-create_time'],
            },
        ),
    ]
