# Generated by Django 2.2.1 on 2019-06-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_chfindexplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chfindexplate',
            old_name='is_sub_page',
            new_name='is_redirect_sub_page',
        ),
        migrations.AddField(
            model_name='chfindexplate',
            name='sub_page_url',
            field=models.CharField(default=None, max_length=150, verbose_name='子页面地址'),
        ),
        migrations.AddField(
            model_name='chfindexplate',
            name='video_source',
            field=models.FileField(default=None, max_length=200, upload_to='media/%Y/%m', verbose_name='视频文件地址'),
        ),
    ]
