# Generated by Django 3.0.5 on 2020-06-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200628_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='chfcompet',
            name='en_sub_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='视频标题(英文)'),
        ),
        migrations.AddField(
            model_name='chfcompet',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='视频标题(中文)'),
        ),
        migrations.AlterField(
            model_name='chfcompet',
            name='en_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='标题(英文)'),
        ),
    ]
