# Generated by Django 2.2.2 on 2019-06-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190627_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='chfbanner',
            name='text',
            field=models.CharField(default=None, max_length=150, verbose_name='Banner上文本描述'),
        ),
    ]
