# Generated by Django 2.2.1 on 2019-06-21 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190620_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChfTableTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('name', models.CharField(default=None, max_length=30, verbose_name='名称')),
                ('file', models.FileField(max_length=255, upload_to='file/%Y/%m', verbose_name='文件')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '申请表格',
                'verbose_name_plural': '申请表格',
                'db_table': 'chf_tabletemplate',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='chfcooperation',
            options={'ordering': ['sort', '-create_time'], 'verbose_name': '合作共赢', 'verbose_name_plural': '合作共赢'},
        ),
        migrations.AddField(
            model_name='chfuserwateringrecord',
            name='client_port',
            field=models.IntegerField(default=0, verbose_name='客户端端口'),
        ),
    ]
