# Generated by Django 2.2.2 on 2019-07-09 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_chfbanner_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChfQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('name', models.CharField(max_length=200, verbose_name='问题标题')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='问题描述')),
                ('type', models.SmallIntegerField(choices=[(-1, '不是问题'), (0, '浏览器问题'), (1, '操作系统问题'), (2, '真bug'), (3, '其他问题')], default=-1, verbose_name='问题类型')),
                ('state', models.SmallIntegerField(choices=[(-1, '待解决'), (0, '未解决'), (1, '已解决'), (2, '延期处理')], default=-1, verbose_name='问题状态')),
            ],
            options={
                'verbose_name': '问题汇总列表',
                'verbose_name_plural': '问题汇总列表',
                'db_table': 'chf_question',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='chfbanner',
            options={'ordering': ['nav', 'sort', '-create_time'], 'verbose_name': 'Banner管理', 'verbose_name_plural': 'Banner管理'},
        ),
    ]
