# Generated by Django 2.2.1 on 2019-05-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_chfproducttype_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chfproducttype',
            options={'ordering': ['sort', '-create_time'], 'verbose_name': '产品类型', 'verbose_name_plural': '产品类型'},
        ),
    ]
