# Generated by Django 2.2.1 on 2019-06-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190603_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfindexplate',
            name='sub_page_url',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='子页面地址'),
        ),
    ]
