# Generated by Django 2.2.2 on 2019-07-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190709_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfcooperation',
            name='type',
            field=models.CharField(choices=[('0', '合作政策'), ('1', '项目优势'), ('2', '经销商问答'), ('3', '支持与服务')], default=0, max_length=10, verbose_name='类型'),
        ),
    ]
