# Generated by Django 2.2.1 on 2019-06-03 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190603_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChfAnimateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('name', models.CharField(default=None, max_length=30, verbose_name='动画名称')),
                ('class_name', models.CharField(default='flip', max_length=50, verbose_name='class样式名')),
                ('desc', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='动画描述')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '动画类型',
                'verbose_name_plural': '动画类型',
                'db_table': 'chf_animatetype',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='chfindexplate',
            name='animate_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ChfAnimateType', verbose_name='动画类型'),
        ),
    ]
