# Generated by Django 2.2.1 on 2019-05-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190508_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='chfproducttype',
            name='data_filter_name',
            field=models.CharField(default='*', max_length=20, verbose_name='数据类型标识'),
        ),
    ]
