# Generated by Django 2.2.1 on 2019-05-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_chfproducttype_data_filter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chfproduct',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
