# Generated by Django 2.2.2 on 2019-07-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190724_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chfaboutresource',
            name='type_name',
        ),
    ]
