# Generated by Django 2.2.1 on 2019-06-03 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190603_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChfAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('comp_name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('slug', models.SlugField(blank=True, help_text='根据name生成的，用于生成页面URL，必须唯一', max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=100, verbose_name='公司简介标题')),
                ('descr', models.TextField(blank=True, default=None, null=True, verbose_name='公司简介')),
                ('comp_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='company/%Y/%m', verbose_name='公司简介图片')),
                ('culture', models.ImageField(blank=True, default=None, null=True, upload_to='company/%Y/%m', verbose_name='公司文化')),
                ('honor', models.ImageField(blank=True, default=None, null=True, upload_to='company/%Y/%m', verbose_name='品牌荣誉')),
                ('aptitude', models.ImageField(blank=True, default=None, null=True, upload_to='company/%Y/%m', verbose_name='企业资质')),
                ('team', models.ImageField(blank=True, default=None, null=True, upload_to='company/%Y/%m', verbose_name='团队风采')),
                ('brand_story', models.ImageField(blank=True, default=None, null=True, upload_to='company/%Y/%m', verbose_name='品牌故事')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '关于我们',
                'verbose_name_plural': '关于我们',
                'db_table': 'chf_about',
            },
        ),
        migrations.RenameField(
            model_name='chfanimatetype',
            old_name='desc',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='chfindexplate',
            old_name='desc',
            new_name='descr',
        ),
    ]
