# Generated by Django 2.2.1 on 2019-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_chfproduct_is_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='chfnews',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
