# Generated by Django 2.2.1 on 2019-06-03 22:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190603_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chfabout',
            old_name='descr',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='chfabout',
            name='aptitude',
        ),
        migrations.RemoveField(
            model_name='chfabout',
            name='brand_story',
        ),
        migrations.RemoveField(
            model_name='chfabout',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='chfabout',
            name='honor',
        ),
        migrations.RemoveField(
            model_name='chfabout',
            name='team',
        ),
        migrations.CreateModel(
            name='ChfAboutResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('type_code', models.PositiveSmallIntegerField(default=0, verbose_name='图片业务类型')),
                ('type_name', models.CharField(default=None, max_length=15, verbose_name='图片业务类型名称')),
                ('image_url', models.ImageField(blank=True, default=None, null=True, upload_to='company/%Y/%m', verbose_name='图片')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('about', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ChfAbout', verbose_name='品牌介绍')),
            ],
            options={
                'verbose_name': '品牌介绍图片资源',
                'verbose_name_plural': '品牌介绍图片资源',
                'db_table': 'chf_aboutresource',
                'ordering': ['sort', '-create_time'],
            },
        ),
    ]
