# Generated by Django 2.2.1 on 2019-05-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_chfnews_is_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chfjobrecruit',
            name='job_require',
        ),
        migrations.RemoveField(
            model_name='chfjobrecruit',
            name='skill_require',
        ),
        migrations.AddField(
            model_name='chfjobrecruit',
            name='content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='招聘要求'),
        ),
    ]
