# Generated by Django 2.2.1 on 2019-06-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190603_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chfabout',
            options={'verbose_name': '品牌介绍', 'verbose_name_plural': '品牌介绍'},
        ),
        migrations.AlterField(
            model_name='chfaboutresource',
            name='about',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_resource', related_query_name='about', to='home.ChfAbout', verbose_name='品牌介绍'),
        ),
        migrations.AlterField(
            model_name='chfapplyrecord',
            name='is_get',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=False, verbose_name='是否已领取'),
        ),
        migrations.AlterField(
            model_name='chfapplyrecord',
            name='is_inform',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=False, verbose_name='是否已通知'),
        ),
    ]
