# Generated by Django 2.2.1 on 2019-06-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190608_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfabout',
            name='is_enable',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfaboutresource',
            name='is_enable',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfanimatetype',
            name='is_enable',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfcompanyhistory',
            name='is_enable',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfindexplate',
            name='is_enable',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfjobrecruit',
            name='is_enable',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfnews',
            name='is_enable',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfpartner',
            name='is_enable',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfproduct',
            name='is_enable',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfproduct',
            name='is_recommand',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=True, verbose_name='是否推荐'),
        ),
    ]
