# Generated by Django 2.2.1 on 2019-06-08 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190608_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChfCooperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('cooper_policy', models.TextField(blank=True, default=None, null=True, verbose_name='合作政策')),
                ('cooper_superiority', models.TextField(blank=True, default=None, null=True, verbose_name='项目优势')),
                ('cooper_question', models.TextField(blank=True, default=None, null=True, verbose_name='经销商问答')),
                ('is_enable', models.BooleanField(choices=[(0, '否'), (1, '是')], default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '合作共赢',
                'verbose_name_plural': '合作共赢',
                'db_table': 'chf_cooperation',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='chfpartner',
            options={'ordering': ['sort', '-create_time'], 'verbose_name': '合作伙伴', 'verbose_name_plural': '合作伙伴'},
        ),
        migrations.RemoveField(
            model_name='chfuserprofile',
            name='is_enable',
        ),
        migrations.RemoveField(
            model_name='chfuserprofile',
            name='is_lock',
        ),
    ]
