# Generated by Django 2.2.1 on 2019-06-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190608_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfcooperation',
            name='is_enable',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=True, verbose_name='是否启用'),
        ),
    ]
