# Generated by Django 2.2.2 on 2019-08-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190803_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysconfig',
            name='address',
            field=models.CharField(max_length=150, verbose_name='底部显示地址'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='icp',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='备案号'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='site_author',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='site_company',
            field=models.CharField(max_length=100, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='site_desc',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='站点描述'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='site_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='站点名称'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='telephone',
            field=models.CharField(max_length=15, verbose_name='底部显示电话'),
        ),
    ]
