# Generated by Django 2.2.1 on 2019-06-08 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190608_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChfCooperationPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='合作政策')),
                ('is_enable', models.BooleanField(choices=[(1, '是'), (0, '否')], default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '合作政策',
                'verbose_name_plural': '合作政策',
                'db_table': 'chf_cooperationpolicy',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ChfCooperationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='经销商问答')),
                ('is_enable', models.BooleanField(choices=[(1, '是'), (0, '否')], default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '经销商问答',
                'verbose_name_plural': '经销商问答',
                'db_table': 'chf_cooperationquestion',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ChfCooperationSuperiority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='项目优势')),
                ('is_enable', models.BooleanField(choices=[(1, '是'), (0, '否')], default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '项目优势',
                'verbose_name_plural': '项目优势',
                'db_table': 'chf_cooperationsuperiority',
                'ordering': ['-create_time'],
            },
        ),
        migrations.DeleteModel(
            name='ChfCooperation',
        ),
    ]
