# Generated by Django 2.2.1 on 2019-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190608_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfcooperationpolicy',
            name='content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='chfcooperationquestion',
            name='content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='chfcooperationsuperiority',
            name='content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='内容'),
        ),
    ]
