# Generated by Django 2.2.2 on 2019-08-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_chfstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfstory',
            name='long_content',
            field=models.TextField(default='', max_length=4000, verbose_name='长板故事'),
        ),
        migrations.AlterField(
            model_name='chfstory',
            name='short_content',
            field=models.TextField(default='', max_length=1000, verbose_name='短板故事'),
        ),
    ]
