# Generated by Django 2.2.1 on 2019-06-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190608_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfcooperationpolicy',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
