# Generated by Django 2.2.5 on 2019-09-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190803_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='chfabout',
            name='en_comp_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='公司名称'),
        ),
        migrations.AddField(
            model_name='chfabout',
            name='en_content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='公司简介'),
        ),
        migrations.AddField(
            model_name='chfabout',
            name='en_title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='公司简介标题'),
        ),
        migrations.AddField(
            model_name='chfbanner',
            name='en_text',
            field=models.CharField(default=None, max_length=300, verbose_name='Banner上文本描述'),
        ),
        migrations.AddField(
            model_name='chfcompanyhistory',
            name='en_breif',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='chfcompanyhistory',
            name='en_content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='chfcompanyhistory',
            name='en_timeline_title',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, unique=True, verbose_name='时间标题'),
        ),
        migrations.AddField(
            model_name='chfcompanyhistory',
            name='en_title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='chfcooperation',
            name='en_content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='chfcooperation',
            name='en_title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='chfindexplate',
            name='en_descr',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='chfindexplate',
            name='en_title',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='板块标题'),
        ),
        migrations.AddField(
            model_name='chfjobrecruit',
            name='en_content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='招聘要求'),
        ),
        migrations.AddField(
            model_name='chfjobrecruit',
            name='en_job_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='职位名称'),
        ),
        migrations.AddField(
            model_name='chfjobrecruit',
            name='en_work_year',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='工作经验'),
        ),
        migrations.AddField(
            model_name='chfnews',
            name='en_brief',
            field=models.CharField(blank=True, default=None, max_length=240, null=True, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='chfnews',
            name='en_content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='chfnews',
            name='en_title',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='chfpartner',
            name='en_brief',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='chfpartner',
            name='en_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='chfproduct',
            name='en_brief',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='产品摘要'),
        ),
        migrations.AddField(
            model_name='chfproduct',
            name='en_content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='产品描述'),
        ),
        migrations.AddField(
            model_name='chfproduct',
            name='en_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='产品名称'),
        ),
        migrations.AddField(
            model_name='chfproducttype',
            name='en_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='类型名称'),
        ),
        migrations.AddField(
            model_name='chfstory',
            name='en_long_content',
            field=models.TextField(blank=True, default=None, max_length=8000, null=True, verbose_name='长板故事'),
        ),
        migrations.AddField(
            model_name='chfstory',
            name='en_long_title',
            field=models.CharField(blank=True, default=None, max_length=160, null=True, verbose_name='长板故事标题'),
        ),
        migrations.AddField(
            model_name='chfstory',
            name='en_short_content',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='短板故事'),
        ),
        migrations.AddField(
            model_name='chfstory',
            name='en_short_title',
            field=models.CharField(blank=True, default=None, max_length=160, null=True, verbose_name='短板故事标题'),
        ),
        migrations.AddField(
            model_name='sysnav',
            name='en_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='chfabout',
            name='comp_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='chfabout',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='公司简介标题'),
        ),
        migrations.AlterField(
            model_name='chfapplyrecord',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='chfapplyrecord',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=50, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='chfapplyrecord',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='chfcompanyhistory',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='chfcooperation',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='chfindexplate',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='板块标题'),
        ),
        migrations.AlterField(
            model_name='chfjobrecruit',
            name='job_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='职位名称'),
        ),
        migrations.AlterField(
            model_name='chfnews',
            name='brief',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='chfnews',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='chfpartner',
            name='brief',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='chfpartner',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='chfproduct',
            name='brief',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='产品摘要'),
        ),
        migrations.AlterField(
            model_name='chfproduct',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='chfproducttype',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='chfstory',
            name='long_content',
            field=models.TextField(blank=True, default=None, max_length=4000, null=True, verbose_name='长板故事'),
        ),
        migrations.AlterField(
            model_name='chfstory',
            name='long_title',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='长板故事标题'),
        ),
        migrations.AlterField(
            model_name='chfstory',
            name='short_content',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='短板故事'),
        ),
        migrations.AlterField(
            model_name='chfstory',
            name='short_title',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='短板故事标题'),
        ),
        migrations.AlterField(
            model_name='sysnav',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='名称'),
        ),
    ]
