# Generated by Django 2.2.5 on 2019-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190913_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfindexplate',
            name='descr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='chfindexplate',
            name='en_descr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='chfindexplate',
            name='en_title',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='板块标题'),
        ),
        migrations.AlterField(
            model_name='chfindexplate',
            name='title',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='板块标题'),
        ),
    ]
