# Generated by Django 2.2.1 on 2019-06-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190608_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfcooperationpolicy',
            name='is_enable',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=True, verbose_name='是否启用'),
        ),
    ]
