# Generated by Django 2.2.1 on 2019-06-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190608_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfabout',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfaboutresource',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfanimatetype',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfapplyrecord',
            name='is_get',
            field=models.BooleanField(default=False, verbose_name='是否已领取'),
        ),
        migrations.AlterField(
            model_name='chfapplyrecord',
            name='is_inform',
            field=models.BooleanField(default=False, verbose_name='是否已通知'),
        ),
        migrations.AlterField(
            model_name='chfcompanyhistory',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfcooperationpolicy',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfcooperationquestion',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfcooperationsuperiority',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfindexplate',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfjobrecruit',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfnews',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfpartner',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfproduct',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='chfproduct',
            name='is_recommand',
            field=models.BooleanField(default=True, verbose_name='是否推荐'),
        ),
    ]
